### ISSUE TITLE
page state update: needs to refresh manually periodically or after tx

### ISSUE THREAD

**Issue by k-gunjan** [Kylix-Finance/kylix-finance-frontend#10]
Page does not show fresh data automatically. It shows fresh data upon manual refresh.

**Comment by k-gunjan** [comment]
Given its very crucial, please suggest the implementation plan and timeline

**Comment by dev-aly3n** [comment]
most of data now refresh on transactions. please let us know if something doesnt get updated when you do a transaction.

without transaction we don't update the data. in lending app it's common to don't update data like a cex or dex. in future when we add dex, we can have a webSocket in that page to have a live update on bids

**Comment by k-gunjan** [comment]
> without transaction we don't update the data. in lending app it's common to don't update data like a cex or dex. in future when we add dex, we can have a webSocket in that page to have a live update on bids


Upon every new block the previous data becomes stale even when the connected account is not doing any transaction. For eg pool data like liquidity, rates etc get updated because of transactions done by other users in a different browser session. Not showing fresh data on the UI is not only impractical it ll break its own functionalities, for eg user will continue to not be able to borrow because of low liquidity even when some other user has provided liquidity to it.
