### ISSUE TITLE
Portfolio page corrections

### ISSUE THREAD

**Issue by k-gunjan** [Kylix-Finance/kylix-finance-frontend#6]
![Image](https://github.com/user-attachments/assets/a07d39b9-1cc9-48d1-b313-0986f6c499e8)

- [x] Borrow limit is showing zero. use `borrow_limit` of `lending_getUserLtv` rpc response 
- [x] `%` should be on the right side of the value in `LTV` display

![Image](https://github.com/user-attachments/assets/1e9d764e-1961-4204-b841-b5315e464658)
- [ ] `%` should be on the right of the value

![Image](https://github.com/user-attachments/assets/91adcfc0-1b3d-4899-9dfb-7a2a7dbe6bec)
- [x]  add column name `Collateral` for the displayed collateral switch

- [ ] Your borrow section [correction](https://github.com/orgs/Kylix-Finance/projects/2/views/1?pane=issue&itemId=86756489&issue=Kylix-Finance%7Ckylix-finance-substrate%7C117)

**Comment by dev-aly3n** [comment]
all are done

**Comment by k-gunjan** [comment]
> % should be on the right side of the value in LTV display

> % should be on the right of the value

these are pending

**Comment by dev-aly3n** [comment]
hey @k-gunjan I think you don't have the latest deploy. sorry
I inform @mohrezal to redploy the latest version

**Comment by k-gunjan** [comment]
moving it to in-progress from reiview. Please confirm after deployments

**Comment by dev-aly3n** [comment]
done. you can review
