### ISSUE TITLE
cancel transaction at the time of signing a transaction leaves TX button hanged. it should become active immediately after cancelling the tx

### ISSUE THREAD

**Issue by k-gunjan** [Kylix-Finance/kylix-finance-frontend#8]
Upon intiating a tx (say `Supply` button is pressed and ) wallet pops up for signing the transaction. If user cancels (instead of signing ) the transaction the flow on UI seems stuck and supply button remains in-active.

Upon cancel transaction it should make TX button active immediately !

**Comment by dev-aly3n** [comment]
should be fixed! @mohrezal ?
