### ISSUE TITLE
market page corrections

### ISSUE THREAD

**Issue by k-gunjan** [Kylix-Finance/kylix-finance-frontend#9]
![Image](https://github.com/user-attachments/assets/36b2b182-99cc-47aa-8c4e-70bab2dfabd7)
- [x] display live utilisation and borrow rate 
![Image](https://github.com/user-attachments/assets/11f0a4bf-0d51-4fa9-8d80-880d7b6b3749)

- [ ] `Available to borrow` should be minimum of liquidity and borrow-limit
- [ ] show live data for other items on Supply, Wihdraw, Borrow and  Reapy tabs

**Comment by dev-aly3n** [comment]
all are done

**Comment by k-gunjan** [comment]
> show live data for other items on Supply, Wihdraw, Borrow and Reapy tabs

On all four tabs
- [ ] Supply APY and borrow APY are mocked . pl use live data

On withdraw tab:
- [ ] available to withdraw and supplied showing the same values.

On Repay:
- [ ] what is value for Available to repay ? that does not seem to be the balance available 

On Borrow page:
- [ ] `Available to borrow` should be minimum of liquidity and allowance ( i had mentioned borrow-limit, my bad) 

![Image](https://github.com/user-attachments/assets/66ef9c6c-9afc-4e53-9bb1-4341f9578df5)
- [ ] `Suppy APY` and `Borrow APY are not live data

**Comment by dev-aly3n** [comment]
> Available to borrow should be minimum of liquidity and allowance ( i had mentioned borrow-limit, my bad)

it's MIN between `borrowed` and `AssetBalance`

**Comment by dev-aly3n** [comment]
all done
